import {
  ChessTitle,
  ContactRole,
  TeachingMode,
  ContactStatus,
} from '@prisma/client';
export const InitialData = {
  id: 1,
  firstName: 'Spencer',
  lastName: 'Jhon',
  role: 'Headcoach' as ContactRole,
  email: 'spencer@example.com',
  phoneNumber: '+1 (555) 456-7890',
  website: 'Male',
  academyIds: ['Academy 1', 'Academy 2'],
  country: 'USA',
  dateOfBirth: null,
  age: 27,
  gender: 'male',
  currentAcademy: 'Academy name',
  workingMode: 'online' as TeachingMode,
  onlinePercentage: 60,
  offlinePercentage: 0,
  state: '',
  cityLocality: '',
  address: '81 Tom street',
  social: {
    linkedin: 'https://linkedin.com/in/33/opens/34/',
    facebook: 'https://facebook.com/33/opens/34/',
    twitter: 'https://twitter.com/33/opens/34/',
    instagram: 'https://instagram.com/33/opens/34/',
  },
  ratings: {
    classic: 1600,
    rapid: 1600,
    blitz: 1600,
  },
  fideId: '535732',
  title: ['GM' as ChessTitle],
  languagesSpoken: ['English'],
  physicalLocations: [],
  lastContacted: '',
  yearsInOperation: 10,
  numberOfCoaches: 1,
  status: 'new' as ContactStatus,
  customTags: ['Popular on Social Media', 'Sicilian Expert'],
  notes:
    'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo.',
};
