import { ContactsTable } from '@/types/contactSection';

export const contacts: ContactsTable[] = [
  {
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    role: 'Coach',
    title: 'GM',
    status: 'active',
  },
  {
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    role: 'Subcoach',
    title: 'IM',
    status: 'lead',
  },
  {
    firstname: 'Alice',
    lastname: 'Johnson',
    email: 'alice.johnson@example.com',
    role: 'Admin',
    title: 'FM',
    status: 'churned',
  },
  {
    firstname: 'Bob',
    lastname: 'Brown',
    email: 'bob.brown@example.com',
    role: 'Coach',
    title: 'CM',
    status: 'prospect',
  },
  {
    firstname: 'Charlie',
    lastname: 'Williams',
    email: 'charlie.williams@example.com',
    role: 'Subcoach',
    title: 'NM',
    status: 'new',
  },
  {
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    role: 'Coach',
    title: 'GM',
    status: 'active',
  },
  {
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    role: 'Subcoach',
    title: 'IM',
    status: 'lead',
  },
  {
    firstname: 'Alice',
    lastname: 'Johnson',
    email: 'alice.johnson@example.com',
    role: 'Admin',
    title: 'FM',
    status: 'churned',
  },
  {
    firstname: 'Bob',
    lastname: 'Brown',
    email: 'bob.brown@example.com',
    role: 'Coach',
    title: 'CM',
    status: 'prospect',
  },
  {
    firstname: 'Charlie',
    lastname: 'Williams',
    email: 'charlie.williams@example.com',
    role: 'Subcoach',
    title: 'NM',
    status: 'new',
  },
  {
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    role: 'Coach',
    title: 'GM',
    status: 'active',
  },
  {
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    role: 'Subcoach',
    title: 'IM',
    status: 'lead',
  },
  {
    firstname: 'Alice',
    lastname: 'Johnson',
    email: 'alice.johnson@example.com',
    role: 'Admin',
    title: 'FM',
    status: 'churned',
  },
  {
    firstname: 'Bob',
    lastname: 'Brown',
    email: 'bob.brown@example.com',
    role: 'Coach',
    title: 'CM',
    status: 'prospect',
  },
  {
    firstname: 'Charlie',
    lastname: 'Williams',
    email: 'charlie.williams@example.com',
    role: 'Subcoach',
    title: 'NM',
    status: 'new',
  },
  {
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    role: 'Coach',
    title: 'GM',
    status: 'active',
  },
  {
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    role: 'Subcoach',
    title: 'IM',
    status: 'lead',
  },
  {
    firstname: 'Alice',
    lastname: 'Johnson',
    email: 'alice.johnson@example.com',
    role: 'Admin',
    title: 'FM',
    status: 'churned',
  },
  {
    firstname: 'Bob',
    lastname: 'Brown',
    email: 'bob.brown@example.com',
    role: 'Coach',
    title: 'CM',
    status: 'prospect',
  },
];
