import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import TrpcProvider from '@/hooks/trpc-provider';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AdminSidebar } from '@/components/Sidebar';
import { Toaster } from '@/components/ui/toaster';
import Providers from '@/components/Providers';
import AuthRedirect from '@/components/auth/AuthRedirect';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TrpcProvider>
        <Providers>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <AuthRedirect>
              <div>
                <SidebarProvider>
                  <AdminSidebar />
                  <main className="h-full w-full">{children}</main>
                </SidebarProvider>
              </div>
              <Toaster />
            </AuthRedirect>
          </body>
        </Providers>
      </TrpcProvider>
    </html>
  );
}
