import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider, SignIn } from '@clerk/nextjs';
import TrpcProvider from '@/hooks/trpc-provider';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AdminSidebar } from '@/components/Sidebar';
import { currentUser } from '@clerk/nextjs/server';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <ClerkProvider>
      <TrpcProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <div>
              {!user?.id ? (
                <SignIn />
              ) : (
                <SidebarProvider>
                  <AdminSidebar />
                  {children}
                </SidebarProvider>
              )}
            </div>
          </body>
        </html>
      </TrpcProvider>
    </ClerkProvider>
  );
}
