import { Academy } from '@/types/contactSection';
export const academies: Academy[] = [
  {
    id: 'acad_001',
    name: 'Grandmaster Chess Academy',
    shortName: 'GMCA',
    timezone: 'UTC-5',
    domain: 'gmchess.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_002',
    name: 'International Chess Academy',
    shortName: 'ICA',
    timezone: 'UTC+1',
    domain: 'ichessacademy.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_003',
    name: 'Elite Chess Academy',
    shortName: 'ECA',
    timezone: 'UTC+3',
    domain: 'elitechess.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_004',
    name: 'Mastermind Chess Academy',
    shortName: 'MCA',
    timezone: 'UTC-7',
    domain: 'mastermindchess.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_005',
    name: 'Chess Gurus Academy',
    shortName: 'CGA',
    timezone: 'UTC+2',
    domain: 'chessgurus.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_006',
    name: 'Strategic Chess Academy',
    shortName: 'SCA',
    timezone: 'UTC+0',
    domain: 'strategicchess.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_007',
    name: 'Tactical Chess Institute',
    shortName: 'TCI',
    timezone: 'UTC-6',
    domain: 'tacticalchess.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_008',
    name: 'Checkmate Chess Academy',
    shortName: 'CCA',
    timezone: 'UTC+4',
    domain: 'checkmatechess.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_009',
    name: 'Endgame Chess Academy',
    shortName: 'EGA',
    timezone: 'UTC+5',
    domain: 'endgamechess.com',
    createdAt: new Date(),
  },
  {
    id: 'acad_010',
    name: "King's Gambit Chess Academy",
    shortName: 'KGCA',
    timezone: 'UTC-8',
    domain: 'kingsgambit.com',
    createdAt: new Date(),
  },
];
